# yaml 配置
version: '3'
networks:
  nginx:
    external: false
services:
  miniconda:
    build: .
    image: ouczbs:miniconda
    container_name: miniconda
    networks:
      - nginx
    ports:
      - "9999:8888"
    volumes:
      - /root:/root
      #- /root/docker_env:/root/docker/env
      - /data:/data
