server {
    listen        27443 ssl;
    server_name   anki.ssl;

    # Configuration managed by Certbot
    ssl_certificate /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key /etc/nginx/ssl/private.key;
    #include /etc/letsencrypt/options-ssl-nginx.conf;

    location / {
        proxy_http_version   1.0;
        proxy_pass           http://anki:27001/;
        client_max_body_size 222M;
    }
}
server {
    listen       27001;
    server_name   anki;
    location / {
        proxy_http_version 1.0;
        proxy_pass         http://anki:27001/;
        # proxy_set_header anki-original-size $http_Content_Length;
        client_max_body_size 222M;
    }
}